export const FORM_SUBMITTED = 'FORM_SUBMITTED';
export const FORM_RESPONSE_RECEIVED = 'FORM_RESPONSE_RECEIVED';
export const FORM_INIT = 'FORM_INIT';
export const EMPLACEMENT_FETCH = 'EMPLACEMENT_FETCH';
export const EMPLACEMENT_FETCH_ERROR = 'EMPLACEMENT_FETCH_ERROR';
export const EMPLACEMENT_FETCH_SUCCESS = 'EMPLACEMENT_FETCH_SUCCESS';
export const EMPLACEMENT_ERROR_CLEAN = 'EMPLACEMENT_ERROR_CLEAN';
