export const FORM_SUBMIT = 'FORM_SUBMIT';
export const FORM_SUBMIT_SUCCESS = 'FORM_SUBMIT_SUCCESS';
export const FORM_SUBMIT_ERROR = 'FORM_SUBMIT_ERROR';
export const FORM_INIT = 'FORM_INIT';

export const EMPLACEMENT_FETCH = 'EMPLACEMENT_FETCH';
export const EMPLACEMENT_FETCH_ERROR = 'EMPLACEMENT_FETCH_ERROR';
export const EMPLACEMENT_FETCH_SUCCESS = 'EMPLACEMENT_FETCH_SUCCESS';
export const EMPLACEMENT_ERROR_CLEAN = 'EMPLACEMENT_ERROR_CLEAN';
