export const FORM_SUBMIT = 'FORM_SUBMIT';
export const FORM_SUBMIT_SUCCESS = 'FORM_SUBMIT_SUCCESS';
export const FORM_SUBMIT_ERROR = 'FORM_SUBMIT_ERROR';
export const FORM_INIT = 'FORM_INIT';

export const EMPLACEMENT_FETCH = 'EMPLACEMENT_FETCH';
export const EMPLACEMENT_FETCH_ERROR = 'EMPLACEMENT_FETCH_ERROR';
export const EMPLACEMENT_FETCH_SUCCESS = 'EMPLACEMENT_FETCH_SUCCESS';
export const EMPLACEMENT_ERROR_CLEAN = 'EMPLACEMENT_ERROR_CLEAN';

export const COMPTA_FETCH = 'COMPTA_FETCH';
export const COMPTA_FETCH_SUCCESS = 'COMPTA_FETCH_SUCCESS';
export const COMPTA_FETCH_ERROR = 'COMPTA_FETCH_ERROR';
export const COMPTA_ERROR_CLEAN = 'COMPTA_ERROR_CLEAN';

export const STATS_FETCH = 'STATS_FETCH';
export const STATS_FETCH_SUCCESS = 'STATS_FETCH_SUCCESS';
export const STATS_FETCH_ERROR = 'STATS_FETCH_ERROR';
export const STATS_ERROR_CLEAN = 'STATS_ERROR_CLEAN';

export const CALENDAR_ADD_EVENT  = 'CALENDAR_ADD_EVENT';
export const CALENDAR_ADD_EVENT_SUCCESS  = 'CALENDAR_ADD_EVENT_SUCCESS';
export const CALENDAR_ADD_EVENT_ERROR  = 'CALENDAR_ADD_EVENT_ERROR';

export const TOAST_ERROR = 'TOAST_ERROR';
export const TOAST_SUCCESS = 'TOAST_SUCCESS';
